version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/chatapp
      - SECRET_KEY=your_secret_key

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: comp3005
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  frontend:
    build: ./frontend/chat-application-client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/chat-application-client:/app
      - /app/node_modules


