services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: comp3005
      POSTGRES_DB: chatapp
    ports:
      - "9000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:comp3005@db:5432/chatapp
      - SECRET_KEY=abf3a7ab4a5583f7c49f4eda605172b6b986c0be5ca1363a
    volumes:
      - ./backend/chat-application-server/chatapp:/app  # Maps directly to /app


  frontend:
    build: ./frontend/chat-application-client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/chat-application-client:/app
      - /app/node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

